@startuml

  package controllers #FDED9B{
    class user-controller <<controller>>
  }
  package middleware #FDB0E0{
    class passport
  }
  package config #F1F2F9{
    class conf
  }
  package models #D4D7EC{
    class User <<model>>
  }
  package routes #fec5bb{
    class authRoute <<route>>
  }
  package test #E43A50{
    class authTest
  }


hide members
test .[hidden]..> config: <<use>>
controllers ..> middleware: <<use>>
middleware ..> config: <<use>>
controllers ..> models: <<use>>
routes ..> controllers: <<use>>

@enduml
